name: Build and publish manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean Docker Image Publish
        # You may pin to the exact commit or the version.
        # uses: ripplr-io/docr-docker-publish@44fac8d6ff7c3ece58c9ffe50f370514d166f5b7
        uses: ripplr-io/docr-docker-publish@v1
        with:
          # Image path in the format registry-name/image-name
          image_path: celt2-server/celt-2-server-${{github.event.inputs.version}}
          dockerfile: ./server
