name: web-api-ci-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SOLUTIONPATH: celt2/API/CELTAPI.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.6.1
    - name: Restore dependencies
      run: dotnet restore    
    - name: Build code
      run: dotnet build ${{env.SOLUTIONPATH}}
