name: web-api-ci-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      SOLUTIONPATH: celt2/API/CELTAPI.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build code
      run: dotnet build ${{env.SOLUTIONPATH}}
      
    - name: Make Directory for test results
      run: mkdir -p testresults
    - name: Run Nunit Tests
      run: dotnet test ${{env.SOLUTIONPATH}} --logger html --results-directory testresults --no-build
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: TestRunReports
        path: testresults
